### PR TITLE
make logging a no-op

### PR DESCRIPTION
**Pull request by nlhepler**
this should get rid of those pesky log files.

### CODE REVIEW

**Review by sjackman — COMMENTED** [review]
```
$ make STAR
make: *** No rule to make target 'STAR'.  Stop.
The command "make STAR" exited with 2.
```
https://travis-ci.com/10XGenomics/STAR/builds/141668012#L234
That's almost certainly not related to this PR. It'd be nice to have CI 💚. Other than that, looks good to me!

**Review by sjackman — APPROVED** [review]

**Review by pmarks — APPROVED** [review]
lgtm

**Comment by nlhepler** [comment]
Includes fixes for the previous tip of orbit due to absolute insanity inside STAR.

**Comment by nlhepler** [comment]
Merged with lh/orbit-2.7.2a

**Pull request closed without merging**
